apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  labels:
    label-one: "value-one"
  name: pubsubtopic-sample # {"type":"string","x-kustomize":{"setter":{"name":"name","value":"pubsubtopic-sample"}}}
