apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: controlling-group-vpc-membership
spec:
  member: serviceAccount:cnrm-system@factory-project-291.iam.gserviceaccount.com # {"$ref":"#/definitions/io.k8s.cli.substitutions.service-account"}
  role: roles/storage.admin
  resourceRef:
    kind: Project
    name: factory-project-291 # {"$ref":"#/definitions/io.k8s.cli.setters.project-id"}
