apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: default-service-account-membership
spec:
  member: serviceAccount:cnrm-system@kcc-thomasrodgers.iam.gserviceaccount.com
  role: roles/iam.serviceAccountUser
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    name: kcc-solutions-sample
