apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: group-storage-admin-on-project-bucket
spec:
  member: serviceAccount:cnrm-system@project-factory-project.iam.gserviceaccount.com
  role: roles/storage.admin
  resourceRef:
    kind: StorageBucket
    name: project-bucket
