apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/organization-id:
  labels: {}
  name: kcc-solutions-sample
spec:
  name: KCC Solutions Sample
  billingAccountRef:
    external:

