apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: service-account-grant-to-group
spec:
  member: serviceAccount:cnrm-system@project-factory-project.iam.gserviceaccount.com # {"$ref":"#/definitions/io.k8s.cli.substitutions.service-account"}
  role: roles/iam.serviceAccountUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: cnrm-system
