apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
kind: Project
metadata:
  annotations:
    cnrm.cloud.google.com/organization-id: ""
    cnrm.cloud.google.com/deletion-policy: abandon
  name: host-project-291
spec:
  name: Project Factory Host
  billingAccountRef:
    external: ""
