apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: iampolicymember-sample
spec:
  # replace ${PROJECT_ID?} with your project name
  member: serviceAccount:iampolicymember-dep-pubsub@${PROJECT_ID?}.iam.gserviceaccount.com
  role: roles/iam.serviceAccountUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind:  IAMServiceAccount
    name: iamserviceaccount-sample
