apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: sample-subscription # {"$ref":"#/definitions/io.k8s.cli.setters.subscription-name"}
spec:
  pushConfig:
    pushEndpoint: "https://example.com/push" # {"$ref":"#/definitions/io.k8s.cli.setters.push-endpoint"}
    oidcToken:
      serviceAccountEmail: pubsub-app@example-project.iam.gserviceaccount.com # {"$ref":"#/definitions/io.k8s.cli.setters.service-account-email"}
