apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  labels:
    label-one: "value-one"
  name: subscription-sample # {"$ref":"#/definitions/io.k8s.cli.setters.subscription-name"}
spec:
  ackDeadlineSeconds: 15 # {"$ref":"#/definitions/io.k8s.cli.setters.deadline"}
  messageRetentionDuration: 86400s # {"$ref":"#/definitions/io.k8s.cli.setters.retention"}
  retainAckedMessages: false # {"$ref":"#/definitions/io.k8s.cli.setters.retain"}
  topicRef:
    name: pubsubsubscription-dep
