apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: sample-subscription # {"$ref":"#/definitions/io.k8s.cli.setters.subscription-name"}
spec:
  messageRetentionDuration: 86400s # {"$ref":"#/definitions/io.k8s.cli.substitutions.retention"}
  retainAckedMessages: false # {"$ref":"#/definitions/io.k8s.cli.setters.retain"}
  topicRef:
    name: sample-topic # {"$ref":"#/definitions/io.k8s.cli.setters.topic-name"}
