apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  labels:
    label-one: "value-one"
  name: topic-sample # {"type":"string","x-kustomize":{"setter":{"name":"topic-name","value":"topic-sample"}}}
